<?php
$modversion['name'] = "Php AddsNew";
$modversion['version'] = "13.08";
$modversion['description'] = "Banner System";
$modversion['credits'] = "w4z004 ( http://www.xoops.sytes.net) for the 4mps Team";
$modversion['author'] = "Original version http://www.sourceforge.net/projects/phpadsnew/";
$modversion['help'] = "";
$modversion['license'] = "GPL LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "phpadsnew_slogo.gif";
$modversion['dirname'] = "phpads";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "misc/all.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "phpads_userlog";
$modversion['tables'][1] = "phpads_affiliates";
$modversion['tables'][2] = "phpads_zones";
$modversion['tables'][3] = "phpads_adclicks";
$modversion['tables'][4] = "phpads_adviews";
$modversion['tables'][5] = "phpads_images";
$modversion['tables'][6] = "phpads_banners";
$modversion['tables'][7] = "phpads_clients";
$modversion['tables'][8] = "phpads_session";
$modversion['tables'][9] = "phpads_acls";
$modversion['tables'][10] = "phpads_adstats";
$modversion['tables'][10] = "phpads_config";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu2.php";

// Menu
$modversion['hasMain'] = 0;


?>